//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ammunition_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        public int ID_Admin { get; set; }
        public string loginAdmin { get; set; }
        public string passAdmin { get; set; }
    }
}
